apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-ingress
  namespace: petstore
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - petstore.contoso.com
      secretName: petstore-tls
  rules:
    - host: petstore.contoso.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petstore-api
                port:
                  number: 80
